# Generated by Django 5.2.5 on 2026-08-18 14:39

import django.core.validators
import django.db.models.deletion
import uuid
from datetime import date
from django.conf import settings
from django.db import migrations, models


def populate_reference_numbers(apps, schema_editor):
    Booking = apps.get_model('booking', 'Booking')
    for booking in Booking.objects.all():
        if not booking.reference_number:
            date_str = booking.booking_date.strftime('%Y%m%d') if booking.booking_date else date.today().strftime('%Y%m%d')
            unique_suffix = uuid.uuid4().hex[:4].upper()
            booking.reference_number = f"LAB-{date_str}-{unique_suffix}"
            booking.save(update_fields=['reference_number'])


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the test category",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Category description and scope"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="bi-journal-medical",
                        help_text="Bootstrap icon class name (e.g., bi-droplet-half)",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Test Category",
                "verbose_name_plural": "Test Categories",
                "ordering": ["name"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="booking",
            name="reference_number",
            field=models.CharField(
                blank=True,
                null=True,
                editable=False,
                help_text="Unique booking reference code (e.g. LAB-20250101-ABCD)",
                max_length=20,
            ),
        ),
        migrations.RunPython(populate_reference_numbers, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="booking",
            name="reference_number",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Unique booking reference code (e.g. LAB-20250101-ABCD)",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Associated user account if registered",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Unique test code (e.g. CBC-01)",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="preparation_instructions",
            field=models.TextField(
                blank=True,
                default="No special fasting required unless instructed by your physician.",
                help_text="Patient preparation guidelines (e.g. Fasting 8-10 hours)",
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="turnaround_time",
            field=models.CharField(
                default="24 Hours",
                help_text="Estimated time to deliver results (e.g. 12 Hours, 2 Days)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="patient",
            field=models.ForeignKey(
                help_text="Patient who made the booking",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="booking.patient",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("sample_collected", "Sample Collected"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                help_text="Current status of the booking",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="test",
            field=models.ForeignKey(
                help_text="Medical test to be performed",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="booking.test",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=models.EmailField(
                help_text="Email address for notifications and account verification",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(
                help_text="Contact phone number",
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+?1?\\d{9,15}$",
                        "Enter a valid phone number (e.g. +1234567890 or 9876543210)",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="description",
            field=models.TextField(
                help_text="Detailed description of the test and what it diagnoses"
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="duration_hours",
            field=models.IntegerField(
                default=1,
                help_text="Expected duration of the sample collection procedure in hours",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(24),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Price of the test",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["status"], name="booking_boo_status_e01616_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["booking_date", "booking_time"],
                name="booking_boo_booking_e0ff63_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["reference_number"], name="booking_boo_referen_590dc2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["email"], name="booking_pat_email_1f635d_idx"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["phone"], name="booking_pat_phone_c8ea6f_idx"),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["pending", "confirmed", "sample_collected", "processing"],
                    )
                ),
                fields=("test", "booking_date", "booking_time"),
                name="unique_active_booking_slot",
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Category of the test",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tests",
                to="booking.category",
            ),
        ),
        migrations.AddIndex(
            model_name="test",
            index=models.Index(
                fields=["is_active", "test_name"], name="booking_tes_is_acti_5adaca_idx"
            ),
        ),
    ]
